FROM node:22-alpine AS build

WORKDIR /app

COPY package.json /app/package.json
COPY src /app/src
COPY angular.json /app/angular.json
COPY tsconfig.json /app/tsconfig.json
COPY tsconfig.app.json /app/tsconfig.app.json
COPY tsconfig.spec.json /app/tsconfig.spec.json
COPY nginx /app/nginx

RUN npm install
RUN npm run build --configuration=production --verbose


FROM nginx:1.25.5-alpine

COPY --from=build /app/nginx/nginx.conf /etc/nginx/templates/default.conf.template
WORKDIR /usr/share/nginx/html

RUN rm -rf ./*

COPY --from=build /app/dist/weather-forecast/browser .

WORKDIR /

EXPOSE 80