/* eslint-disable */

import { Observable, of } from 'rxjs';
import { OpenWeatherMapService } from './open-weather-map.service';
import {
  Forecast5DaysResponse,
  Forecast8DaysResponse,
  GeolocationResponse,
} from './types';

export class OpenWeatherMapDevService extends OpenWeatherMapService {
  override getIconLink(key: string): string {
    return 'http://testlinkerror';
  }

  protected override make5DaysForecastRequest(
    lat: number,
    lon: number
  ): Observable<Forecast5DaysResponse> {
    return of({
      cod: '200',
      message: 0,
      cnt: 40,
      list: [
        {
          dt: 1716595200,
          main: {
            temp: 290.15,
            feels_like: 289.84,
            temp_min: 288.23,
            temp_max: 290.15,
            pressure: 1017,
            sea_level: 1017,
            grnd_level: 1008,
            humidity: 74,
            temp_kf: 1.92,
          },
          weather: [
            {
              id: 801,
              main: 'Clouds',
              description: 'few clouds',
              icon: '02n',
            },
          ],
          clouds: {
            all: 20,
          },
          wind: {
            speed: 3.57,
            deg: 123,
            gust: 9.1,
          },
          visibility: 10000,
          pop: 0.89,
          sys: {
            pod: 'n',
          },
          dt_txt: '2024-05-25 00:00:00',
        },
        {
          dt: 1716606000,
          main: {
            temp: 288.6,
            feels_like: 288.34,
            temp_min: 287.34,
            temp_max: 288.6,
            pressure: 1019,
            sea_level: 1019,
            grnd_level: 1008,
            humidity: 82,
            temp_kf: 1.26,
          },
          weather: [
            {
              id: 800,
              main: 'Clear',
              description: 'clear sky',
              icon: '01d',
            },
          ],
          clouds: {
            all: 9,
          },
          wind: {
            speed: 2.42,
            deg: 115,
            gust: 5.99,
          },
          visibility: 10000,
          pop: 0,
          sys: {
            pod: 'd',
          },
          dt_txt: '2024-05-25 03:00:00',
        },
        {
          dt: 1716616800,
          main: {
            temp: 291.5,
            feels_like: 291.24,
            temp_min: 291.5,
            temp_max: 291.5,
            pressure: 1020,
            sea_level: 1020,
            grnd_level: 1009,
            humidity: 71,
            temp_kf: 0,
          },
          weather: [
            {
              id: 801,
              main: 'Clouds',
              description: 'few clouds',
              icon: '02d',
            },
          ],
          clouds: {
            all: 21,
          },
          wind: {
            speed: 2.45,
            deg: 154,
            gust: 3.77,
          },
          visibility: 10000,
          pop: 0,
          sys: {
            pod: 'd',
          },
          dt_txt: '2024-05-25 06:00:00',
        },
        {
          dt: 1716627600,
          main: {
            temp: 296.89,
            feels_like: 296.57,
            temp_min: 296.89,
            temp_max: 296.89,
            pressure: 1020,
            sea_level: 1020,
            grnd_level: 1009,
            humidity: 48,
            temp_kf: 0,
          },
          weather: [
            {
              id: 802,
              main: 'Clouds',
              description: 'scattered clouds',
              icon: '03d',
            },
          ],
          clouds: {
            all: 47,
          },
          wind: {
            speed: 2.94,
            deg: 152,
            gust: 3.79,
          },
          visibility: 10000,
          pop: 0,
          sys: {
            pod: 'd',
          },
          dt_txt: '2024-05-25 09:00:00',
        },
        {
          dt: 1716638400,
          main: {
            temp: 299.63,
            feels_like: 299.63,
            temp_min: 299.63,
            temp_max: 299.63,
            pressure: 1019,
            sea_level: 1019,
            grnd_level: 1008,
            humidity: 37,
            temp_kf: 0,
          },
          weather: [
            {
              id: 803,
              main: 'Clouds',
              description: 'broken clouds',
              icon: '04d',
            },
          ],
          clouds: {
            all: 59,
          },
          wind: {
            speed: 3.82,
            deg: 150,
            gust: 5.55,
          },
          visibility: 10000,
          pop: 0,
          sys: {
            pod: 'd',
          },
          dt_txt: '2024-05-25 12:00:00',
        },
        {
          dt: 1716649200,
          main: {
            temp: 299.41,
            feels_like: 299.41,
            temp_min: 299.41,
            temp_max: 299.41,
            pressure: 1018,
            sea_level: 1018,
            grnd_level: 1007,
            humidity: 36,
            temp_kf: 0,
          },
          weather: [
            {
              id: 801,
              main: 'Clouds',
              description: 'few clouds',
              icon: '02d',
            },
          ],
          clouds: {
            all: 20,
          },
          wind: {
            speed: 4.9,
            deg: 163,
            gust: 6.73,
          },
          visibility: 10000,
          pop: 0,
          sys: {
            pod: 'd',
          },
          dt_txt: '2024-05-25 15:00:00',
        },
        {
          dt: 1716660000,
          main: {
            temp: 296,
            feels_like: 295.78,
            temp_min: 296,
            temp_max: 296,
            pressure: 1018,
            sea_level: 1018,
            grnd_level: 1007,
            humidity: 55,
            temp_kf: 0,
          },
          weather: [
            {
              id: 801,
              main: 'Clouds',
              description: 'few clouds',
              icon: '02d',
            },
          ],
          clouds: {
            all: 23,
          },
          wind: {
            speed: 2.11,
            deg: 192,
            gust: 5.33,
          },
          visibility: 10000,
          pop: 0,
          sys: {
            pod: 'd',
          },
          dt_txt: '2024-05-25 18:00:00',
        },
        {
          dt: 1716670800,
          main: {
            temp: 291.35,
            feels_like: 291.31,
            temp_min: 291.35,
            temp_max: 291.35,
            pressure: 1019,
            sea_level: 1019,
            grnd_level: 1008,
            humidity: 80,
            temp_kf: 0,
          },
          weather: [
            {
              id: 500,
              main: 'Rain',
              description: 'light rain',
              icon: '10n',
            },
          ],
          clouds: {
            all: 90,
          },
          wind: {
            speed: 1.66,
            deg: 108,
            gust: 2.73,
          },
          visibility: 10000,
          pop: 0.92,
          rain: {
            '3h': 0.92,
          },
          sys: {
            pod: 'n',
          },
          dt_txt: '2024-05-25 21:00:00',
        },
        {
          dt: 1716681600,
          main: {
            temp: 288.86,
            feels_like: 288.76,
            temp_min: 288.86,
            temp_max: 288.86,
            pressure: 1020,
            sea_level: 1020,
            grnd_level: 1009,
            humidity: 87,
            temp_kf: 0,
          },
          weather: [
            {
              id: 500,
              main: 'Rain',
              description: 'light rain',
              icon: '10n',
            },
          ],
          clouds: {
            all: 95,
          },
          wind: {
            speed: 3.57,
            deg: 165,
            gust: 8.43,
          },
          visibility: 10000,
          pop: 1,
          rain: {
            '3h': 0.69,
          },
          sys: {
            pod: 'n',
          },
          dt_txt: '2024-05-26 00:00:00',
        },
        {
          dt: 1716692400,
          main: {
            temp: 288.28,
            feels_like: 288.12,
            temp_min: 288.28,
            temp_max: 288.28,
            pressure: 1020,
            sea_level: 1020,
            grnd_level: 1008,
            humidity: 87,
            temp_kf: 0,
          },
          weather: [
            {
              id: 500,
              main: 'Rain',
              description: 'light rain',
              icon: '10d',
            },
          ],
          clouds: {
            all: 91,
          },
          wind: {
            speed: 1.73,
            deg: 131,
            gust: 4.55,
          },
          visibility: 10000,
          pop: 1,
          rain: {
            '3h': 0.99,
          },
          sys: {
            pod: 'd',
          },
          dt_txt: '2024-05-26 03:00:00',
        },
        {
          dt: 1716703200,
          main: {
            temp: 291.16,
            feels_like: 291.05,
            temp_min: 291.16,
            temp_max: 291.16,
            pressure: 1021,
            sea_level: 1021,
            grnd_level: 1009,
            humidity: 78,
            temp_kf: 0,
          },
          weather: [
            {
              id: 500,
              main: 'Rain',
              description: 'light rain',
              icon: '10d',
            },
          ],
          clouds: {
            all: 83,
          },
          wind: {
            speed: 2.91,
            deg: 125,
            gust: 4.45,
          },
          visibility: 10000,
          pop: 1,
          rain: {
            '3h': 0.88,
          },
          sys: {
            pod: 'd',
          },
          dt_txt: '2024-05-26 06:00:00',
        },
        {
          dt: 1716714000,
          main: {
            temp: 297.06,
            feels_like: 296.68,
            temp_min: 297.06,
            temp_max: 297.06,
            pressure: 1020,
            sea_level: 1020,
            grnd_level: 1009,
            humidity: 45,
            temp_kf: 0,
          },
          weather: [
            {
              id: 803,
              main: 'Clouds',
              description: 'broken clouds',
              icon: '04d',
            },
          ],
          clouds: {
            all: 76,
          },
          wind: {
            speed: 4.33,
            deg: 146,
            gust: 5.73,
          },
          visibility: 10000,
          pop: 0,
          sys: {
            pod: 'd',
          },
          dt_txt: '2024-05-26 09:00:00',
        },
        {
          dt: 1716724800,
          main: {
            temp: 299.95,
            feels_like: 299.56,
            temp_min: 299.95,
            temp_max: 299.95,
            pressure: 1020,
            sea_level: 1020,
            grnd_level: 1009,
            humidity: 33,
            temp_kf: 0,
          },
          weather: [
            {
              id: 803,
              main: 'Clouds',
              description: 'broken clouds',
              icon: '04d',
            },
          ],
          clouds: {
            all: 62,
          },
          wind: {
            speed: 4.72,
            deg: 142,
            gust: 5.2,
          },
          visibility: 10000,
          pop: 0,
          sys: {
            pod: 'd',
          },
          dt_txt: '2024-05-26 12:00:00',
        },
        {
          dt: 1716735600,
          main: {
            temp: 298.59,
            feels_like: 298.13,
            temp_min: 298.59,
            temp_max: 298.59,
            pressure: 1020,
            sea_level: 1020,
            grnd_level: 1008,
            humidity: 36,
            temp_kf: 0,
          },
          weather: [
            {
              id: 801,
              main: 'Clouds',
              description: 'few clouds',
              icon: '02d',
            },
          ],
          clouds: {
            all: 11,
          },
          wind: {
            speed: 6.06,
            deg: 118,
            gust: 6.01,
          },
          visibility: 10000,
          pop: 0,
          sys: {
            pod: 'd',
          },
          dt_txt: '2024-05-26 15:00:00',
        },
        {
          dt: 1716746400,
          main: {
            temp: 293.75,
            feels_like: 293.33,
            temp_min: 293.75,
            temp_max: 293.75,
            pressure: 1020,
            sea_level: 1020,
            grnd_level: 1009,
            humidity: 56,
            temp_kf: 0,
          },
          weather: [
            {
              id: 800,
              main: 'Clear',
              description: 'clear sky',
              icon: '01d',
            },
          ],
          clouds: {
            all: 7,
          },
          wind: {
            speed: 5.69,
            deg: 121,
            gust: 10.51,
          },
          visibility: 10000,
          pop: 0,
          sys: {
            pod: 'd',
          },
          dt_txt: '2024-05-26 18:00:00',
        },
        {
          dt: 1716757200,
          main: {
            temp: 289.19,
            feels_like: 289.04,
            temp_min: 289.19,
            temp_max: 289.19,
            pressure: 1022,
            sea_level: 1022,
            grnd_level: 1011,
            humidity: 84,
            temp_kf: 0,
          },
          weather: [
            {
              id: 500,
              main: 'Rain',
              description: 'light rain',
              icon: '10n',
            },
          ],
          clouds: {
            all: 75,
          },
          wind: {
            speed: 4,
            deg: 142,
            gust: 11.41,
          },
          visibility: 10000,
          pop: 1,
          rain: {
            '3h': 1.17,
          },
          sys: {
            pod: 'n',
          },
          dt_txt: '2024-05-26 21:00:00',
        },
        {
          dt: 1716768000,
          main: {
            temp: 288.41,
            feels_like: 288.13,
            temp_min: 288.41,
            temp_max: 288.41,
            pressure: 1022,
            sea_level: 1022,
            grnd_level: 1010,
            humidity: 82,
            temp_kf: 0,
          },
          weather: [
            {
              id: 804,
              main: 'Clouds',
              description: 'overcast clouds',
              icon: '04n',
            },
          ],
          clouds: {
            all: 87,
          },
          wind: {
            speed: 3.27,
            deg: 128,
            gust: 9.88,
          },
          visibility: 10000,
          pop: 0.77,
          sys: {
            pod: 'n',
          },
          dt_txt: '2024-05-27 00:00:00',
        },
        {
          dt: 1716778800,
          main: {
            temp: 287.41,
            feels_like: 286.85,
            temp_min: 287.41,
            temp_max: 287.41,
            pressure: 1021,
            sea_level: 1021,
            grnd_level: 1010,
            humidity: 75,
            temp_kf: 0,
          },
          weather: [
            {
              id: 804,
              main: 'Clouds',
              description: 'overcast clouds',
              icon: '04d',
            },
          ],
          clouds: {
            all: 99,
          },
          wind: {
            speed: 3.77,
            deg: 134,
            gust: 11.96,
          },
          visibility: 10000,
          pop: 0,
          sys: {
            pod: 'd',
          },
          dt_txt: '2024-05-27 03:00:00',
        },
        {
          dt: 1716789600,
          main: {
            temp: 291.61,
            feels_like: 290.95,
            temp_min: 291.61,
            temp_max: 291.61,
            pressure: 1021,
            sea_level: 1021,
            grnd_level: 1010,
            humidity: 55,
            temp_kf: 0,
          },
          weather: [
            {
              id: 804,
              main: 'Clouds',
              description: 'overcast clouds',
              icon: '04d',
            },
          ],
          clouds: {
            all: 86,
          },
          wind: {
            speed: 5.14,
            deg: 141,
            gust: 10.92,
          },
          visibility: 10000,
          pop: 0,
          sys: {
            pod: 'd',
          },
          dt_txt: '2024-05-27 06:00:00',
        },
        {
          dt: 1716800400,
          main: {
            temp: 296.45,
            feels_like: 295.78,
            temp_min: 296.45,
            temp_max: 296.45,
            pressure: 1021,
            sea_level: 1021,
            grnd_level: 1010,
            humidity: 36,
            temp_kf: 0,
          },
          weather: [
            {
              id: 801,
              main: 'Clouds',
              description: 'few clouds',
              icon: '02d',
            },
          ],
          clouds: {
            all: 16,
          },
          wind: {
            speed: 6.04,
            deg: 144,
            gust: 7.94,
          },
          visibility: 10000,
          pop: 0,
          sys: {
            pod: 'd',
          },
          dt_txt: '2024-05-27 09:00:00',
        },
        {
          dt: 1716811200,
          main: {
            temp: 298.26,
            feels_like: 297.61,
            temp_min: 298.26,
            temp_max: 298.26,
            pressure: 1020,
            sea_level: 1020,
            grnd_level: 1009,
            humidity: 30,
            temp_kf: 0,
          },
          weather: [
            {
              id: 801,
              main: 'Clouds',
              description: 'few clouds',
              icon: '02d',
            },
          ],
          clouds: {
            all: 11,
          },
          wind: {
            speed: 6.47,
            deg: 140,
            gust: 7.52,
          },
          visibility: 10000,
          pop: 0,
          sys: {
            pod: 'd',
          },
          dt_txt: '2024-05-27 12:00:00',
        },
        {
          dt: 1716822000,
          main: {
            temp: 297.2,
            feels_like: 296.55,
            temp_min: 297.2,
            temp_max: 297.2,
            pressure: 1018,
            sea_level: 1018,
            grnd_level: 1007,
            humidity: 34,
            temp_kf: 0,
          },
          weather: [
            {
              id: 800,
              main: 'Clear',
              description: 'clear sky',
              icon: '01d',
            },
          ],
          clouds: {
            all: 0,
          },
          wind: {
            speed: 6.75,
            deg: 132,
            gust: 7.95,
          },
          visibility: 10000,
          pop: 0,
          sys: {
            pod: 'd',
          },
          dt_txt: '2024-05-27 15:00:00',
        },
        {
          dt: 1716832800,
          main: {
            temp: 293.16,
            feels_like: 292.57,
            temp_min: 293.16,
            temp_max: 293.16,
            pressure: 1019,
            sea_level: 1019,
            grnd_level: 1008,
            humidity: 52,
            temp_kf: 0,
          },
          weather: [
            {
              id: 800,
              main: 'Clear',
              description: 'clear sky',
              icon: '01d',
            },
          ],
          clouds: {
            all: 0,
          },
          wind: {
            speed: 5.66,
            deg: 131,
            gust: 8.87,
          },
          visibility: 10000,
          pop: 0,
          sys: {
            pod: 'd',
          },
          dt_txt: '2024-05-27 18:00:00',
        },
        {
          dt: 1716843600,
          main: {
            temp: 289.5,
            feels_like: 288.89,
            temp_min: 289.5,
            temp_max: 289.5,
            pressure: 1020,
            sea_level: 1020,
            grnd_level: 1008,
            humidity: 65,
            temp_kf: 0,
          },
          weather: [
            {
              id: 800,
              main: 'Clear',
              description: 'clear sky',
              icon: '01n',
            },
          ],
          clouds: {
            all: 2,
          },
          wind: {
            speed: 4.76,
            deg: 140,
            gust: 11.95,
          },
          visibility: 10000,
          pop: 0,
          sys: {
            pod: 'n',
          },
          dt_txt: '2024-05-27 21:00:00',
        },
        {
          dt: 1716854400,
          main: {
            temp: 287.75,
            feels_like: 287.02,
            temp_min: 287.75,
            temp_max: 287.75,
            pressure: 1020,
            sea_level: 1020,
            grnd_level: 1008,
            humidity: 67,
            temp_kf: 0,
          },
          weather: [
            {
              id: 800,
              main: 'Clear',
              description: 'clear sky',
              icon: '01n',
            },
          ],
          clouds: {
            all: 1,
          },
          wind: {
            speed: 3.42,
            deg: 127,
            gust: 10.61,
          },
          visibility: 10000,
          pop: 0,
          sys: {
            pod: 'n',
          },
          dt_txt: '2024-05-28 00:00:00',
        },
        {
          dt: 1716865200,
          main: {
            temp: 286.5,
            feels_like: 285.74,
            temp_min: 286.5,
            temp_max: 286.5,
            pressure: 1019,
            sea_level: 1019,
            grnd_level: 1008,
            humidity: 71,
            temp_kf: 0,
          },
          weather: [
            {
              id: 800,
              main: 'Clear',
              description: 'clear sky',
              icon: '01d',
            },
          ],
          clouds: {
            all: 6,
          },
          wind: {
            speed: 3.37,
            deg: 113,
            gust: 10.5,
          },
          visibility: 10000,
          pop: 0,
          sys: {
            pod: 'd',
          },
          dt_txt: '2024-05-28 03:00:00',
        },
        {
          dt: 1716876000,
          main: {
            temp: 290.55,
            feels_like: 289.83,
            temp_min: 290.55,
            temp_max: 290.55,
            pressure: 1019,
            sea_level: 1019,
            grnd_level: 1008,
            humidity: 57,
            temp_kf: 0,
          },
          weather: [
            {
              id: 800,
              main: 'Clear',
              description: 'clear sky',
              icon: '01d',
            },
          ],
          clouds: {
            all: 7,
          },
          wind: {
            speed: 5.15,
            deg: 115,
            gust: 9.77,
          },
          visibility: 10000,
          pop: 0,
          sys: {
            pod: 'd',
          },
          dt_txt: '2024-05-28 06:00:00',
        },
        {
          dt: 1716886800,
          main: {
            temp: 294.37,
            feels_like: 293.8,
            temp_min: 294.37,
            temp_max: 294.37,
            pressure: 1018,
            sea_level: 1018,
            grnd_level: 1007,
            humidity: 48,
            temp_kf: 0,
          },
          weather: [
            {
              id: 803,
              main: 'Clouds',
              description: 'broken clouds',
              icon: '04d',
            },
          ],
          clouds: {
            all: 60,
          },
          wind: {
            speed: 6.01,
            deg: 131,
            gust: 8.76,
          },
          visibility: 10000,
          pop: 0,
          sys: {
            pod: 'd',
          },
          dt_txt: '2024-05-28 09:00:00',
        },
        {
          dt: 1716897600,
          main: {
            temp: 294.82,
            feels_like: 294.4,
            temp_min: 294.82,
            temp_max: 294.82,
            pressure: 1017,
            sea_level: 1017,
            grnd_level: 1005,
            humidity: 52,
            temp_kf: 0,
          },
          weather: [
            {
              id: 500,
              main: 'Rain',
              description: 'light rain',
              icon: '10d',
            },
          ],
          clouds: {
            all: 73,
          },
          wind: {
            speed: 5.52,
            deg: 109,
            gust: 7.15,
          },
          visibility: 10000,
          pop: 0.31,
          rain: {
            '3h': 0.33,
          },
          sys: {
            pod: 'd',
          },
          dt_txt: '2024-05-28 12:00:00',
        },
        {
          dt: 1716908400,
          main: {
            temp: 294.15,
            feels_like: 293.77,
            temp_min: 294.15,
            temp_max: 294.15,
            pressure: 1015,
            sea_level: 1015,
            grnd_level: 1004,
            humidity: 56,
            temp_kf: 0,
          },
          weather: [
            {
              id: 500,
              main: 'Rain',
              description: 'light rain',
              icon: '10d',
            },
          ],
          clouds: {
            all: 95,
          },
          wind: {
            speed: 4.26,
            deg: 113,
            gust: 5.9,
          },
          visibility: 10000,
          pop: 0.49,
          rain: {
            '3h': 0.31,
          },
          sys: {
            pod: 'd',
          },
          dt_txt: '2024-05-28 15:00:00',
        },
        {
          dt: 1716919200,
          main: {
            temp: 292.83,
            feels_like: 292.5,
            temp_min: 292.83,
            temp_max: 292.83,
            pressure: 1015,
            sea_level: 1015,
            grnd_level: 1004,
            humidity: 63,
            temp_kf: 0,
          },
          weather: [
            {
              id: 500,
              main: 'Rain',
              description: 'light rain',
              icon: '10d',
            },
          ],
          clouds: {
            all: 71,
          },
          wind: {
            speed: 2.88,
            deg: 105,
            gust: 6.36,
          },
          visibility: 10000,
          pop: 0.21,
          rain: {
            '3h': 0.11,
          },
          sys: {
            pod: 'd',
          },
          dt_txt: '2024-05-28 18:00:00',
        },
        {
          dt: 1716930000,
          main: {
            temp: 290.07,
            feels_like: 289.85,
            temp_min: 290.07,
            temp_max: 290.07,
            pressure: 1015,
            sea_level: 1015,
            grnd_level: 1004,
            humidity: 78,
            temp_kf: 0,
          },
          weather: [
            {
              id: 802,
              main: 'Clouds',
              description: 'scattered clouds',
              icon: '03n',
            },
          ],
          clouds: {
            all: 34,
          },
          wind: {
            speed: 2.32,
            deg: 98,
            gust: 6.29,
          },
          visibility: 10000,
          pop: 0,
          sys: {
            pod: 'n',
          },
          dt_txt: '2024-05-28 21:00:00',
        },
        {
          dt: 1716940800,
          main: {
            temp: 288.69,
            feels_like: 288.47,
            temp_min: 288.69,
            temp_max: 288.69,
            pressure: 1015,
            sea_level: 1015,
            grnd_level: 1004,
            humidity: 83,
            temp_kf: 0,
          },
          weather: [
            {
              id: 801,
              main: 'Clouds',
              description: 'few clouds',
              icon: '02n',
            },
          ],
          clouds: {
            all: 19,
          },
          wind: {
            speed: 1.97,
            deg: 106,
            gust: 4.53,
          },
          visibility: 10000,
          pop: 0,
          sys: {
            pod: 'n',
          },
          dt_txt: '2024-05-29 00:00:00',
        },
        {
          dt: 1716951600,
          main: {
            temp: 287.81,
            feels_like: 287.6,
            temp_min: 287.81,
            temp_max: 287.81,
            pressure: 1015,
            sea_level: 1015,
            grnd_level: 1003,
            humidity: 87,
            temp_kf: 0,
          },
          weather: [
            {
              id: 800,
              main: 'Clear',
              description: 'clear sky',
              icon: '01d',
            },
          ],
          clouds: {
            all: 10,
          },
          wind: {
            speed: 1.83,
            deg: 113,
            gust: 4.1,
          },
          visibility: 10000,
          pop: 0,
          sys: {
            pod: 'd',
          },
          dt_txt: '2024-05-29 03:00:00',
        },
        {
          dt: 1716962400,
          main: {
            temp: 292.19,
            feels_like: 291.9,
            temp_min: 292.19,
            temp_max: 292.19,
            pressure: 1015,
            sea_level: 1015,
            grnd_level: 1004,
            humidity: 67,
            temp_kf: 0,
          },
          weather: [
            {
              id: 800,
              main: 'Clear',
              description: 'clear sky',
              icon: '01d',
            },
          ],
          clouds: {
            all: 8,
          },
          wind: {
            speed: 2.15,
            deg: 144,
            gust: 3.18,
          },
          visibility: 10000,
          pop: 0,
          sys: {
            pod: 'd',
          },
          dt_txt: '2024-05-29 06:00:00',
        },
        {
          dt: 1716973200,
          main: {
            temp: 295.72,
            feels_like: 295.49,
            temp_min: 295.72,
            temp_max: 295.72,
            pressure: 1014,
            sea_level: 1014,
            grnd_level: 1003,
            humidity: 56,
            temp_kf: 0,
          },
          weather: [
            {
              id: 500,
              main: 'Rain',
              description: 'light rain',
              icon: '10d',
            },
          ],
          clouds: {
            all: 2,
          },
          wind: {
            speed: 2.47,
            deg: 150,
            gust: 3.16,
          },
          visibility: 10000,
          pop: 0.85,
          rain: {
            '3h': 0.84,
          },
          sys: {
            pod: 'd',
          },
          dt_txt: '2024-05-29 09:00:00',
        },
        {
          dt: 1716984000,
          main: {
            temp: 295.47,
            feels_like: 295.4,
            temp_min: 295.47,
            temp_max: 295.47,
            pressure: 1013,
            sea_level: 1013,
            grnd_level: 1002,
            humidity: 63,
            temp_kf: 0,
          },
          weather: [
            {
              id: 501,
              main: 'Rain',
              description: 'moderate rain',
              icon: '10d',
            },
          ],
          clouds: {
            all: 9,
          },
          wind: {
            speed: 2.68,
            deg: 232,
            gust: 2.76,
          },
          visibility: 5306,
          pop: 1,
          rain: {
            '3h': 4.33,
          },
          sys: {
            pod: 'd',
          },
          dt_txt: '2024-05-29 12:00:00',
        },
        {
          dt: 1716994800,
          main: {
            temp: 292.98,
            feels_like: 292.98,
            temp_min: 292.98,
            temp_max: 292.98,
            pressure: 1013,
            sea_level: 1013,
            grnd_level: 1002,
            humidity: 75,
            temp_kf: 0,
          },
          weather: [
            {
              id: 501,
              main: 'Rain',
              description: 'moderate rain',
              icon: '10d',
            },
          ],
          clouds: {
            all: 99,
          },
          wind: {
            speed: 3.86,
            deg: 283,
            gust: 5.48,
          },
          visibility: 10000,
          pop: 1,
          rain: {
            '3h': 4.47,
          },
          sys: {
            pod: 'd',
          },
          dt_txt: '2024-05-29 15:00:00',
        },
        {
          dt: 1717005600,
          main: {
            temp: 291.16,
            feels_like: 290.95,
            temp_min: 291.16,
            temp_max: 291.16,
            pressure: 1013,
            sea_level: 1013,
            grnd_level: 1002,
            humidity: 74,
            temp_kf: 0,
          },
          weather: [
            {
              id: 803,
              main: 'Clouds',
              description: 'broken clouds',
              icon: '04d',
            },
          ],
          clouds: {
            all: 83,
          },
          wind: {
            speed: 4.46,
            deg: 285,
            gust: 6.94,
          },
          visibility: 10000,
          pop: 0.8,
          sys: {
            pod: 'd',
          },
          dt_txt: '2024-05-29 18:00:00',
        },
        {
          dt: 1717016400,
          main: {
            temp: 288.33,
            feels_like: 288.07,
            temp_min: 288.33,
            temp_max: 288.33,
            pressure: 1013,
            sea_level: 1013,
            grnd_level: 1002,
            humidity: 83,
            temp_kf: 0,
          },
          weather: [
            {
              id: 500,
              main: 'Rain',
              description: 'light rain',
              icon: '10n',
            },
          ],
          clouds: {
            all: 21,
          },
          wind: {
            speed: 3.39,
            deg: 297,
            gust: 7.29,
          },
          visibility: 10000,
          pop: 0.46,
          rain: {
            '3h': 0.24,
          },
          sys: {
            pod: 'n',
          },
          dt_txt: '2024-05-29 21:00:00',
        },
      ],
      city: {
        id: 756135,
        name: 'Warsaw',
        coord: {
          lat: 52.2298,
          lon: 21.0118,
        },
        country: 'PL',
        population: 1000000,
        timezone: 7200,
        sunrise: 1716517715,
        sunset: 1716575843,
      },
    });
  }

  protected override make8DaysForecastRequest(
    lat: number,
    lon: number
  ): Observable<Forecast8DaysResponse> {
    return of({
      lat: 52.232,
      lon: 21.0067,
      timezone: 'Europe/Warsaw',
      timezone_offset: 7200,
      current: {
        dt: 1716582215,
        sunrise: 1716517716,
        sunset: 1716575845,
        temp: 292.06,
        feels_like: 291.63,
        pressure: 1017,
        humidity: 62,
        dew_point: 284.63,
        uvi: 0,
        clouds: 0,
        visibility: 10000,
        wind_speed: 2.57,
        wind_deg: 70,
        weather: [
          {
            id: 800,
            main: 'Clear',
            description: 'clear sky',
            icon: '01n',
          },
        ],
      },
      hourly: [
        {
          dt: 1716580800,
          temp: 292.06,
          feels_like: 291.63,
          pressure: 1017,
          humidity: 62,
          dew_point: 284.63,
          uvi: 0,
          clouds: 0,
          visibility: 7380,
          wind_speed: 4.03,
          wind_deg: 127,
          wind_gust: 9.22,
          weather: [
            {
              id: 500,
              main: 'Rain',
              description: 'light rain',
              icon: '10n',
            },
          ],
          pop: 1,
          rain: {
            '1h': 0.47,
          },
        },
        {
          dt: 1716584400,
          temp: 291.67,
          feels_like: 291.35,
          pressure: 1018,
          humidity: 68,
          dew_point: 285.66,
          uvi: 0,
          clouds: 9,
          visibility: 10000,
          wind_speed: 5.09,
          wind_deg: 126,
          wind_gust: 11.74,
          weather: [
            {
              id: 800,
              main: 'Clear',
              description: 'clear sky',
              icon: '01n',
            },
          ],
          pop: 0.79,
        },
        {
          dt: 1716588000,
          temp: 290.96,
          feels_like: 290.68,
          pressure: 1018,
          humidity: 72,
          dew_point: 285.85,
          uvi: 0,
          clouds: 24,
          visibility: 10000,
          wind_speed: 4.25,
          wind_deg: 128,
          wind_gust: 9.85,
          weather: [
            {
              id: 801,
              main: 'Clouds',
              description: 'few clouds',
              icon: '02n',
            },
          ],
          pop: 0.76,
        },
        {
          dt: 1716591600,
          temp: 290.22,
          feels_like: 289.99,
          pressure: 1019,
          humidity: 77,
          dew_point: 286.16,
          uvi: 0,
          clouds: 41,
          visibility: 10000,
          wind_speed: 3.86,
          wind_deg: 130,
          wind_gust: 10.28,
          weather: [
            {
              id: 802,
              main: 'Clouds',
              description: 'scattered clouds',
              icon: '03n',
            },
          ],
          pop: 0.72,
        },
        {
          dt: 1716595200,
          temp: 289,
          feels_like: 288.81,
          pressure: 1019,
          humidity: 83,
          dew_point: 286.12,
          uvi: 0,
          clouds: 48,
          visibility: 10000,
          wind_speed: 3.57,
          wind_deg: 123,
          wind_gust: 9.1,
          weather: [
            {
              id: 802,
              main: 'Clouds',
              description: 'scattered clouds',
              icon: '03n',
            },
          ],
          pop: 0.89,
        },
        {
          dt: 1716598800,
          temp: 287.86,
          feels_like: 287.71,
          pressure: 1020,
          humidity: 89,
          dew_point: 286.18,
          uvi: 0,
          clouds: 16,
          visibility: 10000,
          wind_speed: 3.38,
          wind_deg: 128,
          wind_gust: 9.16,
          weather: [
            {
              id: 801,
              main: 'Clouds',
              description: 'few clouds',
              icon: '02n',
            },
          ],
          pop: 0,
        },
        {
          dt: 1716602400,
          temp: 287.69,
          feels_like: 287.52,
          pressure: 1020,
          humidity: 89,
          dew_point: 285.92,
          uvi: 0,
          clouds: 14,
          visibility: 10000,
          wind_speed: 3.01,
          wind_deg: 134,
          wind_gust: 8.85,
          weather: [
            {
              id: 801,
              main: 'Clouds',
              description: 'few clouds',
              icon: '02n',
            },
          ],
          pop: 0,
        },
        {
          dt: 1716606000,
          temp: 287.34,
          feels_like: 287.14,
          pressure: 1020,
          humidity: 89,
          dew_point: 285.67,
          uvi: 0,
          clouds: 14,
          visibility: 10000,
          wind_speed: 2.42,
          wind_deg: 115,
          wind_gust: 5.99,
          weather: [
            {
              id: 801,
              main: 'Clouds',
              description: 'few clouds',
              icon: '02d',
            },
          ],
          pop: 0,
        },
        {
          dt: 1716609600,
          temp: 287.98,
          feels_like: 287.74,
          pressure: 1020,
          humidity: 85,
          dew_point: 285.49,
          uvi: 0.27,
          clouds: 18,
          visibility: 10000,
          wind_speed: 2.83,
          wind_deg: 131,
          wind_gust: 5.77,
          weather: [
            {
              id: 801,
              main: 'Clouds',
              description: 'few clouds',
              icon: '02d',
            },
          ],
          pop: 0,
        },
        {
          dt: 1716613200,
          temp: 289.4,
          feels_like: 289.14,
          pressure: 1020,
          humidity: 79,
          dew_point: 285.8,
          uvi: 0.74,
          clouds: 21,
          visibility: 10000,
          wind_speed: 2.61,
          wind_deg: 151,
          wind_gust: 4.28,
          weather: [
            {
              id: 801,
              main: 'Clouds',
              description: 'few clouds',
              icon: '02d',
            },
          ],
          pop: 0,
        },
        {
          dt: 1716616800,
          temp: 291.5,
          feels_like: 291.24,
          pressure: 1020,
          humidity: 71,
          dew_point: 286.25,
          uvi: 1.58,
          clouds: 21,
          visibility: 10000,
          wind_speed: 2.45,
          wind_deg: 154,
          wind_gust: 3.77,
          weather: [
            {
              id: 801,
              main: 'Clouds',
              description: 'few clouds',
              icon: '02d',
            },
          ],
          pop: 0,
        },
        {
          dt: 1716620400,
          temp: 293.5,
          feels_like: 293.24,
          pressure: 1020,
          humidity: 63,
          dew_point: 286.4,
          uvi: 2.74,
          clouds: 29,
          visibility: 10000,
          wind_speed: 2.44,
          wind_deg: 148,
          wind_gust: 3.5,
          weather: [
            {
              id: 802,
              main: 'Clouds',
              description: 'scattered clouds',
              icon: '03d',
            },
          ],
          pop: 0,
        },
        {
          dt: 1716624000,
          temp: 295.44,
          feels_like: 295.16,
          pressure: 1020,
          humidity: 55,
          dew_point: 286,
          uvi: 4.05,
          clouds: 27,
          visibility: 10000,
          wind_speed: 2.64,
          wind_deg: 147,
          wind_gust: 3.59,
          weather: [
            {
              id: 802,
              main: 'Clouds',
              description: 'scattered clouds',
              icon: '03d',
            },
          ],
          pop: 0,
        },
        {
          dt: 1716627600,
          temp: 296.89,
          feels_like: 296.57,
          pressure: 1020,
          humidity: 48,
          dew_point: 285.38,
          uvi: 5.23,
          clouds: 47,
          visibility: 10000,
          wind_speed: 2.94,
          wind_deg: 152,
          wind_gust: 3.79,
          weather: [
            {
              id: 802,
              main: 'Clouds',
              description: 'scattered clouds',
              icon: '03d',
            },
          ],
          pop: 0,
        },
        {
          dt: 1716631200,
          temp: 297.92,
          feels_like: 297.6,
          pressure: 1020,
          humidity: 44,
          dew_point: 285.18,
          uvi: 5.66,
          clouds: 58,
          visibility: 10000,
          wind_speed: 3.2,
          wind_deg: 150,
          wind_gust: 4.22,
          weather: [
            {
              id: 803,
              main: 'Clouds',
              description: 'broken clouds',
              icon: '04d',
            },
          ],
          pop: 0,
        },
        {
          dt: 1716634800,
          temp: 298.93,
          feels_like: 298.63,
          pressure: 1020,
          humidity: 41,
          dew_point: 284.89,
          uvi: 5.64,
          clouds: 62,
          visibility: 10000,
          wind_speed: 3.49,
          wind_deg: 144,
          wind_gust: 5,
          weather: [
            {
              id: 803,
              main: 'Clouds',
              description: 'broken clouds',
              icon: '04d',
            },
          ],
          pop: 0,
        },
        {
          dt: 1716638400,
          temp: 299.63,
          feels_like: 299.63,
          pressure: 1019,
          humidity: 37,
          dew_point: 283.9,
          uvi: 4.99,
          clouds: 59,
          visibility: 10000,
          wind_speed: 3.82,
          wind_deg: 150,
          wind_gust: 5.55,
          weather: [
            {
              id: 803,
              main: 'Clouds',
              description: 'broken clouds',
              icon: '04d',
            },
          ],
          pop: 0,
        },
        {
          dt: 1716642000,
          temp: 299.99,
          feels_like: 299.67,
          pressure: 1018,
          humidity: 35,
          dew_point: 283.29,
          uvi: 2.98,
          clouds: 32,
          visibility: 10000,
          wind_speed: 4.49,
          wind_deg: 163,
          wind_gust: 6.5,
          weather: [
            {
              id: 802,
              main: 'Clouds',
              description: 'scattered clouds',
              icon: '03d',
            },
          ],
          pop: 0,
        },
        {
          dt: 1716645600,
          temp: 299.88,
          feels_like: 299.56,
          pressure: 1018,
          humidity: 34,
          dew_point: 282.98,
          uvi: 2.3,
          clouds: 24,
          visibility: 10000,
          wind_speed: 4.73,
          wind_deg: 166,
          wind_gust: 6.54,
          weather: [
            {
              id: 801,
              main: 'Clouds',
              description: 'few clouds',
              icon: '02d',
            },
          ],
          pop: 0,
        },
        {
          dt: 1716649200,
          temp: 299.41,
          feels_like: 299.41,
          pressure: 1018,
          humidity: 36,
          dew_point: 283.22,
          uvi: 1.24,
          clouds: 20,
          visibility: 10000,
          wind_speed: 4.9,
          wind_deg: 163,
          wind_gust: 6.73,
          weather: [
            {
              id: 801,
              main: 'Clouds',
              description: 'few clouds',
              icon: '02d',
            },
          ],
          pop: 0,
        },
        {
          dt: 1716652800,
          temp: 298.84,
          feels_like: 298.46,
          pressure: 1018,
          humidity: 38,
          dew_point: 283.75,
          uvi: 0.75,
          clouds: 17,
          visibility: 10000,
          wind_speed: 4.4,
          wind_deg: 175,
          wind_gust: 5.61,
          weather: [
            {
              id: 801,
              main: 'Clouds',
              description: 'few clouds',
              icon: '02d',
            },
          ],
          pop: 0,
        },
        {
          dt: 1716656400,
          temp: 297.84,
          feels_like: 297.54,
          pressure: 1018,
          humidity: 45,
          dew_point: 285.23,
          uvi: 0.2,
          clouds: 18,
          visibility: 10000,
          wind_speed: 3.48,
          wind_deg: 170,
          wind_gust: 5.32,
          weather: [
            {
              id: 801,
              main: 'Clouds',
              description: 'few clouds',
              icon: '02d',
            },
          ],
          pop: 0,
        },
        {
          dt: 1716660000,
          temp: 296,
          feels_like: 295.78,
          pressure: 1018,
          humidity: 55,
          dew_point: 286.58,
          uvi: 0,
          clouds: 23,
          visibility: 10000,
          wind_speed: 2.11,
          wind_deg: 192,
          wind_gust: 5.33,
          weather: [
            {
              id: 801,
              main: 'Clouds',
              description: 'few clouds',
              icon: '02d',
            },
          ],
          pop: 0,
        },
        {
          dt: 1716663600,
          temp: 294.6,
          feels_like: 294.42,
          pressure: 1019,
          humidity: 62,
          dew_point: 287.16,
          uvi: 0,
          clouds: 100,
          visibility: 10000,
          wind_speed: 1.29,
          wind_deg: 249,
          wind_gust: 2.22,
          weather: [
            {
              id: 804,
              main: 'Clouds',
              description: 'overcast clouds',
              icon: '04n',
            },
          ],
          pop: 0.32,
        },
        {
          dt: 1716667200,
          temp: 293.35,
          feels_like: 293.18,
          pressure: 1019,
          humidity: 67,
          dew_point: 287.38,
          uvi: 0,
          clouds: 100,
          visibility: 10000,
          wind_speed: 0.84,
          wind_deg: 284,
          wind_gust: 1.43,
          weather: [
            {
              id: 500,
              main: 'Rain',
              description: 'light rain',
              icon: '10n',
            },
          ],
          pop: 0.5,
          rain: {
            '1h': 0.14,
          },
        },
        {
          dt: 1716670800,
          temp: 291.35,
          feels_like: 291.31,
          pressure: 1019,
          humidity: 80,
          dew_point: 287.87,
          uvi: 0,
          clouds: 90,
          visibility: 10000,
          wind_speed: 1.66,
          wind_deg: 108,
          wind_gust: 2.73,
          weather: [
            {
              id: 500,
              main: 'Rain',
              description: 'light rain',
              icon: '10n',
            },
          ],
          pop: 0.92,
          rain: {
            '1h': 0.78,
          },
        },
        {
          dt: 1716674400,
          temp: 290.54,
          feels_like: 290.55,
          pressure: 1020,
          humidity: 85,
          dew_point: 288.17,
          uvi: 0,
          clouds: 92,
          visibility: 10000,
          wind_speed: 1.8,
          wind_deg: 136,
          wind_gust: 3.75,
          weather: [
            {
              id: 500,
              main: 'Rain',
              description: 'light rain',
              icon: '10n',
            },
          ],
          pop: 1,
          rain: {
            '1h': 0.31,
          },
        },
        {
          dt: 1716678000,
          temp: 289.56,
          feels_like: 289.55,
          pressure: 1020,
          humidity: 88,
          dew_point: 287.58,
          uvi: 0,
          clouds: 93,
          visibility: 10000,
          wind_speed: 2.94,
          wind_deg: 146,
          wind_gust: 6.12,
          weather: [
            {
              id: 500,
              main: 'Rain',
              description: 'light rain',
              icon: '10n',
            },
          ],
          pop: 1,
          rain: {
            '1h': 0.17,
          },
        },
        {
          dt: 1716681600,
          temp: 288.86,
          feels_like: 288.76,
          pressure: 1020,
          humidity: 87,
          dew_point: 286.76,
          uvi: 0,
          clouds: 95,
          visibility: 10000,
          wind_speed: 3.57,
          wind_deg: 165,
          wind_gust: 8.43,
          weather: [
            {
              id: 500,
              main: 'Rain',
              description: 'light rain',
              icon: '10n',
            },
          ],
          pop: 1,
          rain: {
            '1h': 0.21,
          },
        },
        {
          dt: 1716685200,
          temp: 288.55,
          feels_like: 288.37,
          pressure: 1020,
          humidity: 85,
          dew_point: 286.19,
          uvi: 0,
          clouds: 76,
          visibility: 10000,
          wind_speed: 2.6,
          wind_deg: 168,
          wind_gust: 7.46,
          weather: [
            {
              id: 500,
              main: 'Rain',
              description: 'light rain',
              icon: '10n',
            },
          ],
          pop: 1,
          rain: {
            '1h': 0.51,
          },
        },
        {
          dt: 1716688800,
          temp: 288.36,
          feels_like: 288.16,
          pressure: 1020,
          humidity: 85,
          dew_point: 286.1,
          uvi: 0,
          clouds: 86,
          visibility: 10000,
          wind_speed: 1.7,
          wind_deg: 140,
          wind_gust: 4.15,
          weather: [
            {
              id: 500,
              main: 'Rain',
              description: 'light rain',
              icon: '10n',
            },
          ],
          pop: 1,
          rain: {
            '1h': 0.32,
          },
        },
        {
          dt: 1716692400,
          temp: 288.28,
          feels_like: 288.12,
          pressure: 1020,
          humidity: 87,
          dew_point: 286.21,
          uvi: 0,
          clouds: 91,
          visibility: 10000,
          wind_speed: 1.73,
          wind_deg: 131,
          wind_gust: 4.55,
          weather: [
            {
              id: 500,
              main: 'Rain',
              description: 'light rain',
              icon: '10d',
            },
          ],
          pop: 1,
          rain: {
            '1h': 0.16,
          },
        },
        {
          dt: 1716696000,
          temp: 288.76,
          feels_like: 288.65,
          pressure: 1020,
          humidity: 87,
          dew_point: 286.61,
          uvi: 0.24,
          clouds: 92,
          visibility: 10000,
          wind_speed: 1.63,
          wind_deg: 142,
          wind_gust: 4.15,
          weather: [
            {
              id: 500,
              main: 'Rain',
              description: 'light rain',
              icon: '10d',
            },
          ],
          pop: 1,
          rain: {
            '1h': 0.17,
          },
        },
        {
          dt: 1716699600,
          temp: 289.77,
          feels_like: 289.68,
          pressure: 1021,
          humidity: 84,
          dew_point: 287.11,
          uvi: 0.71,
          clouds: 84,
          visibility: 9435,
          wind_speed: 1.97,
          wind_deg: 131,
          wind_gust: 3.4,
          weather: [
            {
              id: 500,
              main: 'Rain',
              description: 'light rain',
              icon: '10d',
            },
          ],
          pop: 1,
          rain: {
            '1h': 0.51,
          },
        },
        {
          dt: 1716703200,
          temp: 291.16,
          feels_like: 291.05,
          pressure: 1021,
          humidity: 78,
          dew_point: 287.35,
          uvi: 1.53,
          clouds: 83,
          visibility: 10000,
          wind_speed: 2.91,
          wind_deg: 125,
          wind_gust: 4.45,
          weather: [
            {
              id: 500,
              main: 'Rain',
              description: 'light rain',
              icon: '10d',
            },
          ],
          pop: 1,
          rain: {
            '1h': 0.2,
          },
        },
        {
          dt: 1716706800,
          temp: 292.75,
          feels_like: 292.52,
          pressure: 1021,
          humidity: 67,
          dew_point: 286.58,
          uvi: 2.69,
          clouds: 100,
          visibility: 10000,
          wind_speed: 3.52,
          wind_deg: 127,
          wind_gust: 5.45,
          weather: [
            {
              id: 804,
              main: 'Clouds',
              description: 'overcast clouds',
              icon: '04d',
            },
          ],
          pop: 0,
        },
        {
          dt: 1716710400,
          temp: 295.15,
          feels_like: 294.76,
          pressure: 1021,
          humidity: 52,
          dew_point: 285.04,
          uvi: 3.97,
          clouds: 100,
          visibility: 10000,
          wind_speed: 3.98,
          wind_deg: 136,
          wind_gust: 5.83,
          weather: [
            {
              id: 804,
              main: 'Clouds',
              description: 'overcast clouds',
              icon: '04d',
            },
          ],
          pop: 0,
        },
        {
          dt: 1716714000,
          temp: 297.06,
          feels_like: 296.68,
          pressure: 1020,
          humidity: 45,
          dew_point: 284.52,
          uvi: 5.13,
          clouds: 76,
          visibility: 10000,
          wind_speed: 4.33,
          wind_deg: 146,
          wind_gust: 5.73,
          weather: [
            {
              id: 803,
              main: 'Clouds',
              description: 'broken clouds',
              icon: '04d',
            },
          ],
          pop: 0,
        },
        {
          dt: 1716717600,
          temp: 298.47,
          feels_like: 298.1,
          pressure: 1020,
          humidity: 40,
          dew_point: 283.98,
          uvi: 5.65,
          clouds: 73,
          visibility: 10000,
          wind_speed: 4.49,
          wind_deg: 150,
          wind_gust: 5.53,
          weather: [
            {
              id: 803,
              main: 'Clouds',
              description: 'broken clouds',
              icon: '04d',
            },
          ],
          pop: 0,
        },
        {
          dt: 1716721200,
          temp: 299.45,
          feels_like: 299.45,
          pressure: 1020,
          humidity: 35,
          dew_point: 283,
          uvi: 5.63,
          clouds: 70,
          visibility: 10000,
          wind_speed: 4.52,
          wind_deg: 149,
          wind_gust: 5.08,
          weather: [
            {
              id: 803,
              main: 'Clouds',
              description: 'broken clouds',
              icon: '04d',
            },
          ],
          pop: 0,
        },
        {
          dt: 1716724800,
          temp: 299.95,
          feels_like: 299.56,
          pressure: 1020,
          humidity: 33,
          dew_point: 282.36,
          uvi: 5.24,
          clouds: 62,
          visibility: 10000,
          wind_speed: 4.72,
          wind_deg: 142,
          wind_gust: 5.2,
          weather: [
            {
              id: 803,
              main: 'Clouds',
              description: 'broken clouds',
              icon: '04d',
            },
          ],
          pop: 0,
        },
        {
          dt: 1716728400,
          temp: 299.96,
          feels_like: 299.53,
          pressure: 1020,
          humidity: 32,
          dew_point: 282.13,
          uvi: 4.26,
          clouds: 10,
          visibility: 10000,
          wind_speed: 5.29,
          wind_deg: 136,
          wind_gust: 5.04,
          weather: [
            {
              id: 800,
              main: 'Clear',
              description: 'clear sky',
              icon: '01d',
            },
          ],
          pop: 0,
        },
        {
          dt: 1716732000,
          temp: 299.47,
          feels_like: 299.47,
          pressure: 1020,
          humidity: 33,
          dew_point: 282.2,
          uvi: 2.95,
          clouds: 12,
          visibility: 10000,
          wind_speed: 5.78,
          wind_deg: 130,
          wind_gust: 5.43,
          weather: [
            {
              id: 801,
              main: 'Clouds',
              description: 'few clouds',
              icon: '02d',
            },
          ],
          pop: 0,
        },
        {
          dt: 1716735600,
          temp: 298.59,
          feels_like: 298.13,
          pressure: 1020,
          humidity: 36,
          dew_point: 282.66,
          uvi: 1.77,
          clouds: 11,
          visibility: 10000,
          wind_speed: 6.06,
          wind_deg: 118,
          wind_gust: 6.01,
          weather: [
            {
              id: 801,
              main: 'Clouds',
              description: 'few clouds',
              icon: '02d',
            },
          ],
          pop: 0,
        },
        {
          dt: 1716739200,
          temp: 297.46,
          feels_like: 297.04,
          pressure: 1020,
          humidity: 42,
          dew_point: 283.9,
          uvi: 0.88,
          clouds: 10,
          visibility: 10000,
          wind_speed: 6.46,
          wind_deg: 123,
          wind_gust: 7.57,
          weather: [
            {
              id: 800,
              main: 'Clear',
              description: 'clear sky',
              icon: '01d',
            },
          ],
          pop: 0,
        },
        {
          dt: 1716742800,
          temp: 296.13,
          feels_like: 295.79,
          pressure: 1021,
          humidity: 50,
          dew_point: 285.21,
          uvi: 0.34,
          clouds: 8,
          visibility: 10000,
          wind_speed: 5.36,
          wind_deg: 125,
          wind_gust: 7.52,
          weather: [
            {
              id: 800,
              main: 'Clear',
              description: 'clear sky',
              icon: '01d',
            },
          ],
          pop: 0,
        },
        {
          dt: 1716746400,
          temp: 293.75,
          feels_like: 293.33,
          pressure: 1020,
          humidity: 56,
          dew_point: 284.78,
          uvi: 0,
          clouds: 7,
          visibility: 10000,
          wind_speed: 5.69,
          wind_deg: 121,
          wind_gust: 10.51,
          weather: [
            {
              id: 800,
              main: 'Clear',
              description: 'clear sky',
              icon: '01d',
            },
          ],
          pop: 0,
        },
        {
          dt: 1716750000,
          temp: 291.9,
          feels_like: 291.42,
          pressure: 1021,
          humidity: 61,
          dew_point: 284.53,
          uvi: 0,
          clouds: 71,
          visibility: 10000,
          wind_speed: 5.66,
          wind_deg: 131,
          wind_gust: 12.29,
          weather: [
            {
              id: 803,
              main: 'Clouds',
              description: 'broken clouds',
              icon: '04n',
            },
          ],
          pop: 0.3,
        },
      ],
      daily: [
        {
          dt: 1716544800,
          sunrise: 1716517716,
          sunset: 1716575845,
          moonrise: 1716582480,
          moonset: 1716517080,
          moon_phase: 0.53,
          summary: 'Expect a day of partly cloudy with rain',
          temp: {
            day: 298.51,
            min: 287.16,
            max: 300.34,
            night: 291.67,
            eve: 297.16,
            morn: 287.88,
          },
          feels_like: {
            day: 298.2,
            night: 291.35,
            eve: 296.82,
            morn: 287.81,
          },
          pressure: 1020,
          humidity: 42,
          dew_point: 284.83,
          wind_speed: 6.07,
          wind_deg: 138,
          wind_gust: 11.74,
          weather: [
            {
              id: 500,
              main: 'Rain',
              description: 'light rain',
              icon: '10d',
            },
          ],
          clouds: 95,
          pop: 1,
          rain: 0.91,
          uvi: 6.23,
        },
        {
          dt: 1716631200,
          sunrise: 1716604047,
          sunset: 1716662326,
          moonrise: 1716672840,
          moonset: 1716605820,
          moon_phase: 0.56,
          summary:
            'You can expect partly cloudy in the morning, with rain in the afternoon',
          temp: {
            day: 297.92,
            min: 287.34,
            max: 299.99,
            night: 291.35,
            eve: 298.84,
            morn: 287.98,
          },
          feels_like: {
            day: 297.6,
            night: 291.31,
            eve: 298.46,
            morn: 287.74,
          },
          pressure: 1020,
          humidity: 44,
          dew_point: 285.18,
          wind_speed: 4.9,
          wind_deg: 163,
          wind_gust: 10.28,
          weather: [
            {
              id: 500,
              main: 'Rain',
              description: 'light rain',
              icon: '10d',
            },
          ],
          clouds: 58,
          pop: 0.92,
          rain: 0.92,
          uvi: 5.66,
        },
        {
          dt: 1716717600,
          sunrise: 1716690380,
          sunset: 1716748806,
          moonrise: 0,
          moonset: 1716695520,
          moon_phase: 0.6,
          summary: 'Expect a day of partly cloudy with rain',
          temp: {
            day: 298.47,
            min: 288.28,
            max: 299.96,
            night: 289.19,
            eve: 297.46,
            morn: 288.76,
          },
          feels_like: {
            day: 298.1,
            night: 289.04,
            eve: 297.04,
            morn: 288.65,
          },
          pressure: 1020,
          humidity: 40,
          dew_point: 283.98,
          wind_speed: 6.46,
          wind_deg: 123,
          wind_gust: 12.62,
          weather: [
            {
              id: 500,
              main: 'Rain',
              description: 'light rain',
              icon: '10d',
            },
          ],
          clouds: 73,
          pop: 1,
          rain: 3.66,
          uvi: 5.65,
        },
        {
          dt: 1716804000,
          sunrise: 1716776716,
          sunset: 1716835284,
          moonrise: 1716762180,
          moonset: 1716786360,
          moon_phase: 0.63,
          summary:
            'You can expect partly cloudy in the morning, with clearing in the afternoon',
          temp: {
            day: 297.36,
            min: 287.41,
            max: 298.26,
            night: 289.5,
            eve: 296.27,
            morn: 287.98,
          },
          feels_like: {
            day: 296.67,
            night: 288.89,
            eve: 295.66,
            morn: 287.4,
          },
          pressure: 1020,
          humidity: 32,
          dew_point: 279.8,
          wind_speed: 6.75,
          wind_deg: 132,
          wind_gust: 11.96,
          weather: [
            {
              id: 801,
              main: 'Clouds',
              description: 'few clouds',
              icon: '02d',
            },
          ],
          clouds: 14,
          pop: 0.8,
          uvi: 5.98,
        },
        {
          dt: 1716890400,
          sunrise: 1716863055,
          sunset: 1716921760,
          moonrise: 1716850620,
          moonset: 1716877800,
          moon_phase: 0.67,
          summary: 'Expect a day of partly cloudy with rain',
          temp: {
            day: 294.37,
            min: 286.5,
            max: 294.82,
            night: 290.07,
            eve: 294.15,
            morn: 286.5,
          },
          feels_like: {
            day: 293.8,
            night: 289.85,
            eve: 293.77,
            morn: 285.74,
          },
          pressure: 1018,
          humidity: 48,
          dew_point: 283.17,
          wind_speed: 6.01,
          wind_deg: 131,
          wind_gust: 10.61,
          weather: [
            {
              id: 500,
              main: 'Rain',
              description: 'light rain',
              icon: '10d',
            },
          ],
          clouds: 60,
          pop: 0.49,
          rain: 0.75,
          uvi: 4.93,
        },
        {
          dt: 1716976800,
          sunrise: 1716949396,
          sunset: 1717008235,
          moonrise: 1716938460,
          moonset: 1716969540,
          moon_phase: 0.7,
          summary: 'Expect a day of partly cloudy with rain',
          temp: {
            day: 295.72,
            min: 287.81,
            max: 295.72,
            night: 288.33,
            eve: 292.98,
            morn: 287.81,
          },
          feels_like: {
            day: 295.49,
            night: 288.07,
            eve: 292.98,
            morn: 287.6,
          },
          pressure: 1014,
          humidity: 56,
          dew_point: 286.53,
          wind_speed: 4.46,
          wind_deg: 285,
          wind_gust: 7.29,
          weather: [
            {
              id: 501,
              main: 'Rain',
              description: 'moderate rain',
              icon: '10d',
            },
          ],
          clouds: 2,
          pop: 1,
          rain: 9.88,
          uvi: 6.13,
        },
        {
          dt: 1717063200,
          sunrise: 1717035740,
          sunset: 1717094707,
          moonrise: 1717025880,
          moonset: 1717061220,
          moon_phase: 0.75,
          summary: 'Expect a day of partly cloudy with rain',
          temp: {
            day: 293.02,
            min: 286.36,
            max: 294.29,
            night: 290.02,
            eve: 294.29,
            morn: 286.36,
          },
          feels_like: {
            day: 292.58,
            night: 289.69,
            eve: 293.82,
            morn: 286.14,
          },
          pressure: 1011,
          humidity: 58,
          dew_point: 284.7,
          wind_speed: 2.5,
          wind_deg: 331,
          wind_gust: 5.73,
          weather: [
            {
              id: 803,
              main: 'Clouds',
              description: 'broken clouds',
              icon: '04d',
            },
          ],
          clouds: 63,
          pop: 0.27,
          uvi: 7,
        },
        {
          dt: 1717149600,
          sunrise: 1717122087,
          sunset: 1717181177,
          moonrise: 1717113060,
          moonset: 1717152840,
          moon_phase: 0.78,
          summary: 'Expect a day of partly cloudy with rain',
          temp: {
            day: 296.82,
            min: 287.64,
            max: 298.75,
            night: 291.05,
            eve: 297.54,
            morn: 287.64,
          },
          feels_like: {
            day: 296.37,
            night: 291.09,
            eve: 297.24,
            morn: 287.39,
          },
          pressure: 1008,
          humidity: 43,
          dew_point: 283.46,
          wind_speed: 6.18,
          wind_deg: 247,
          wind_gust: 9.86,
          weather: [
            {
              id: 500,
              main: 'Rain',
              description: 'light rain',
              icon: '10d',
            },
          ],
          clouds: 11,
          pop: 0.99,
          rain: 1.2,
          uvi: 7,
        },
      ],
    });
  }

  protected override makeGeolocationForCityRequest(
    city: string
  ): Observable<GeolocationResponse[]> {
    return of([
      {
        name: 'London',
        local_names: {
          uz: 'London',
          ht: 'Lonn',
          lv: 'Londona',
          sv: 'London',
          vo: 'London',
          tk: 'London',
          az: 'London',
          io: 'London',
          cv: 'Лондон',
          an: 'Londres',
          gl: 'Londres',
          ja: 'ロンドン',
          id: 'London',
          cu: 'Лондонъ',
          kl: 'London',
          gu: 'લંડન',
          bm: 'London',
          so: 'London',
          hu: 'London',
          it: 'Londra',
          sq: 'Londra',
          tg: 'Лондон',
          kw: 'Loundres',
          gn: 'Lóndyre',
          ln: 'Lóndɛlɛ',
          nv: 'Tooh Dineʼé Bikin Haalʼá',
          lb: 'London',
          mi: 'Rānana',
          es: 'Londres',
          fj: 'Lodoni',
          sw: 'London',
          ca: 'Londres',
          bh: 'लंदन',
          gd: 'Lunnainn',
          uk: 'Лондон',
          ig: 'London',
          bi: 'London',
          ay: 'London',
          ku: 'London',
          mn: 'Лондон',
          yo: 'Lọndọnu',
          pt: 'Londres',
          br: 'Londrez',
          fr: 'Londres',
          ff: 'London',
          zu: 'ILondon',
          am: 'ለንደን',
          ka: 'ლონდონი',
          ba: 'Лондон',
          hy: 'Լոնդոն',
          bs: 'London',
          oc: 'Londres',
          eo: 'Londono',
          se: 'London',
          fa: 'لندن',
          mt: 'Londra',
          th: 'ลอนดอน',
          et: 'London',
          kn: 'ಲಂಡನ್',
          mk: 'Лондон',
          ro: 'Londra',
          ne: 'लन्डन',
          qu: 'London',
          sh: 'London',
          sd: 'لنڊن',
          lo: 'ລອນດອນ',
          nl: 'Londen',
          vi: 'Luân Đôn',
          ur: 'علاقہ لندن',
          de: 'London',
          sc: 'Londra',
          hi: 'लंदन',
          my: 'လန်ဒန်မြို့',
          tl: 'Londres',
          ia: 'London',
          su: 'London',
          km: 'ឡុងដ៍',
          be: 'Лондан',
          wo: 'Londar',
          ps: 'لندن',
          bg: 'Лондон',
          mg: 'Lôndôna',
          ga: 'Londain',
          tw: 'London',
          sr: 'Лондон',
          sa: 'लन्डन्',
          or: 'ଲଣ୍ଡନ',
          kv: 'Лондон',
          ee: 'London',
          is: 'London',
          ny: 'London',
          ru: 'Лондон',
          ml: 'ലണ്ടൻ',
          ta: 'இலண்டன்',
          si: 'ලන්ඩන්',
          sk: 'Londýn',
          na: 'London',
          rm: 'Londra',
          en: 'London',
          hr: 'London',
          st: 'London',
          bn: 'লন্ডন',
          av: 'Лондон',
          om: 'Landan',
          ky: 'Лондон',
          af: 'Londen',
          ab: 'Лондон',
          tr: 'Londra',
          sn: 'London',
          no: 'London',
          li: 'Londe',
          pl: 'Londyn',
          tt: 'Лондон',
          bo: 'ལོན་ཊོན།',
          fi: 'Lontoo',
          pa: 'ਲੰਡਨ',
          sm: 'Lonetona',
          cs: 'Londýn',
          cy: 'Llundain',
          ms: 'London',
          el: 'Λονδίνο',
          mr: 'लंडन',
          zh: '伦敦',
          lt: 'Londonas',
          co: 'Londra',
          sl: 'London',
          feature_name: 'London',
          eu: 'Londres',
          ug: 'لوندۇن',
          gv: 'Lunnin',
          ha: 'Landan',
          to: 'Lonitoni',
          da: 'London',
          os: 'Лондон',
          he: 'לונדון',
          ce: 'Лондон',
          ko: '런던',
          nn: 'London',
          jv: 'London',
          ascii: 'London',
          kk: 'Лондон',
          yi: 'לאנדאן',
          ie: 'London',
          ar: 'لندن',
          fy: 'Londen',
          fo: 'London',
          te: 'లండన్',
          wa: 'Londe',
        },
        lat: 51.5073219,
        lon: -0.1276474,
        country: 'GB',
        state: 'England',
      },
      {
        name: 'City of London',
        local_names: {
          fr: 'Cité de Londres',
          hi: 'सिटी ऑफ़ लंदन',
          ko: '시티 오브 런던',
          es: 'City de Londres',
          ru: 'Сити',
          ur: 'لندن شہر',
          lt: 'Londono Sitis',
          en: 'City of London',
          uk: 'Лондонське Сіті',
          he: 'הסיטי של לונדון',
          zh: '倫敦市',
          pt: 'Cidade de Londres',
        },
        lat: 51.5156177,
        lon: -0.0919983,
        country: 'GB',
        state: 'England',
      },
      {
        name: 'London',
        local_names: {
          th: 'ลอนดอน',
          ga: 'Londain',
          fr: 'London',
          he: 'לונדון',
          ko: '런던',
          hy: 'Լոնտոն',
          ja: 'ロンドン',
          ka: 'ლონდონი',
          lv: 'Landona',
          bn: 'লন্ডন',
          be: 'Лондан',
          ar: 'لندن',
          ru: 'Лондон',
          yi: 'לאנדאן',
          oj: 'Baketigweyaang',
          ug: 'لوندۇن',
          fa: 'لندن',
          en: 'London',
          iu: 'ᓚᓐᑕᓐ',
          el: 'Λόντον',
          lt: 'Londonas',
          cr: 'ᓬᐊᐣᑕᐣ',
        },
        lat: 42.9832406,
        lon: -81.243372,
        country: 'CA',
        state: 'Ontario',
      },
      {
        name: 'Chelsea',
        local_names: {
          eu: 'Chelsea',
          no: 'Chelsea',
          vi: 'Chelsea, Luân Đôn',
          pl: 'Chelsea',
          pt: 'Chelsea',
          da: 'Chelsea',
          ar: 'تشيلسي',
          az: 'Çelsi',
          et: 'Chelsea',
          de: 'Chelsea',
          id: 'Chelsea, London',
          af: 'Chelsea, Londen',
          zh: '車路士',
          sh: 'Chelsea, London',
          sv: 'Chelsea, London',
          it: 'Chelsea',
          ur: 'چیلسی، لندن',
          sk: 'Chelsea',
          en: 'Chelsea',
          hu: 'Chelsea',
          ja: 'チェルシー',
          el: 'Τσέλσι',
          nl: 'Chelsea',
          tr: 'Chelsea, Londra',
          ko: '첼시',
          fa: 'چلسی',
          ru: 'Челси',
          fr: 'Chelsea',
          hi: 'चेल्सी, लंदन',
          he: "צ'לסי",
          ga: 'Chelsea',
          es: 'Chelsea',
          uk: 'Челсі',
        },
        lat: 51.4875167,
        lon: -0.1687007,
        country: 'GB',
        state: 'England',
      },
      {
        name: 'London',
        lat: 37.1289771,
        lon: -84.0832646,
        country: 'US',
        state: 'Kentucky',
      },
    ]);
  }
}
